### ISSUE TITLE
How to add features by service URL?

### ISSUE THREAD

**Issue by kevinhaeni** [nickcam/FlareClusterLayer#13]
Hi Nick, great project! I would love to use this in our project, however, I fail to understand how I can use it given a ArcGIS Feature Layer URL. By using a QueryTask I can get the JSON but it has a different structure than your data.json file ( coordinates are under the geometry object etc.).

Do I need to change the FCL code or is there any esri-way to load the features in a way that is compatible with your FCL?

I'm using the version 4.1 of the API btw.

**Comment by nickcam** [comment]
Hi @kevinhaeni. Unfortunately it doesn't cater for hooking up to feature layers. I've only had the use case for a custom dataset so far, so haven't gotten around to trying to use a feature layer as a dataset. 
For the moment I think you could query the feature layer to get the data back, then massage the results into an array of custom objects, and pass that array as the data to the layer.

Will definitely have a look at adding feature layer support though when time permits...of course you could also fork and try it out as well :).

**Comment by hohenstrater** [comment]
To pass a feature layer would be awesome. How much work is involved?

**Comment by nickcam** [comment]
Hey man,

I don't think there's too much work involved.
It would just require the cluster layer taking an already constructed feature layer or at the least a feature layer url and instantiating it internally.
Then querying the feature layer and then finally using the returned features as the data source for the already existing clustering. Repeat query and clustering every time the feature layer updates.

Still haven't had a chance to actually try it out though - and not sure when I will. Do you know of any publically accessible point feature layers that have a lot of points to test with?

Performance may be an issue (depending on the feature layer) due to the server call to query though.
That said performing the clustering server side so only already clustered data gets sent to the client would be better anyway. 

I think the best spot for this would be in the feature layer code on the server though. Perhaps you could request from ESRI that they update feature layers on the ArcGIS server side to take some clustering parameters and then return clustered objects as features....this would basically make this cluster layer invalid except for some of the client side sugar in there.

Thanks,
Nick

**Comment by bruce83hub** [comment]
Hi Nick,

After the feature layer has been converted to a query and then displayed as a flare would you be able to make changes and edit the query (like add another point to the flare data) before sending it back to the serve to update the feature?

Thanks
Bruce

**Comment by nickcam** [comment]
Hi @bruce83hub, not quite sure what you mean sorry?

I don't think you could add a point to the overall point list in a feature layer loaded from a url. I'm guessing it would have to be added to the data source of the feature layer which would then be picked up in the next query. 

Is that sort of what you mean?

**Comment by bruce83hub** [comment]
Hi Nickcam,

Thanks for the reply,

Thats right, I am hopping to be able to edit the feature layer and then display the data from the feature layer with something like your flare cluster. Is this possible?

Thanks
Bruce

**Comment by nickcam** [comment]
Hi @bruce83hub,

Yeah ok. Sounds like you'd have to edit the data source of your feature layer, if you're doing this client side I think the layer has to be part of a Feature Service. Then re-query the feature layer to get the points to send to the cluster function.

This is all speculative though as I haven't attempted to add Feature Layer support yet. I don't think I'll be touching this layer until 4.4 is released...there are more hooks for custom layers in that release from what I've seen, so will just wait for that to drop. First priority will be a like for like though as this will fit my immediate requirements...so still no feature layer support until possibly later.

Thanks,
Nick
