### ISSUE TITLE
webpack / typings / Arcgis 3.18 / Angular2

### ISSUE THREAD

**Issue by klanglie** [nickcam/FlareClusterLayer#17]
Hi - My teammate is having trouble getting ClusterLayer.js (from esri examples) working in an Angular 2 app that uses Arcgis 3.18 and webpack. It looks like your 3.18 test app is written in pure JS and does not have a typings file for it. Can you please suggest ways we can get FlareClusterLayer working in our TypeScript environment using 3.18. We would upgrade to 4.1 but apparantly there are features not yet implemented in that version that we rely on. Thanks!

**Comment by nickcam** [comment]
Hi @PivotalAnimal,

Is the problem you can't get the library to load in your app at all or is it that you just don't get intellisense as there's no typings file?

You should still be able to use it without a typings file. As it's just a dojo module, include it and load it up as an external reference like you would other external amd libraries. I have no useful experience with webpack, so can't offer any assistance there sorry. If you haven't seen it already this repository could help - [https://github.com/tomwayson/angular2-esri-example](https://github.com/tomwayson/angular2-esri-example).

If the problem is just the lack of a typings file - you could create one. Have it inherit from GraphicsLayer and just add the new public methods and properties. If you do create one, feel to create a PR to add it to the repository.

Hope this helps, Nick.

**Comment by klanglie** [comment]
Hi @nickcam 

I am looking into the option of creating a typings file. I tried this with ClusterLayer.js from esri but somehow their solution is still not working. Creating a typings file seems pretty straight forward. I think basically all it does is allow tsc to compile and at runtime doesn't do anything. That being said, would I need to include private (those marked with _) in this file or only those exposed by the UI (from the demo _v3 example). BTW - I did take a look at Tom's solution previously. We are using snippets of his code to glue our solution together. Thanks for your help!

Edit - I see you mentioned 'just add the new public methods and properties' - So I will remove '_xxx' ones

Kai

My typings looks something like this now:

`declare module "extras/FlareClusterLayer" {

  import Color = require('esri/Color');
  import SpatialReference = require('esri/SpatialReference');
  import TextSymbol = require('esri/symbols/TextSymbol');
  import GraphicsLayer = require('esri/layers/GraphicsLayer');
  import Renderer = require('esri/renderers/ClassBreaksRenderer');

  interface FlareClusterOptions {
      spatialReference?: SpatialReference;
      preClustered?: boolean;
      clusterRatio?: number;
      displaySubTypeFlares?: boolean;
      subTypeFlareProperty?: string;
      flareColor?: Color;
      maxFlareCount?: number;
      displaySingleFlaresAtCount?: number;
      singleFlareTooltipProperty?: string;
      textSymbol?: TextSymbol;
      flareShowMode?: string;
      clusteringBegin?: () => void;
      clusteringComplete?: () => void;
      clusterAreaDisplay?: string;
      clusterAreaRender?: Renderer;
      xPropertyName?: string;
      yPropertyName?: string;
      idPropertyName?: string;
  }

  class FlareClusterLayer extends GraphicsLayer {

      constructor(options: FlareClusterOptions);

      setRenderer(renderer: any, clusterAreaRenderer: any): void;

      onClick(e: any): void;

      add(p: any): void;

      clear(): void;

      on(action: string | Function, method: string | Function);

      maxScale: number;

      addPreClusteredData(data: any): void;

      addData(data: any): void;
  }
  export = FlareClusterLayer;
}
`

**Comment by klanglie** [comment]
Issue solved. Thanks!

**Comment by nickcam** [comment]
Awesome, glad you got it sorted!
