### ISSUE TITLE
how to solove the question : execute too many times

### ISSUE THREAD

**Issue by guzhongren** [nickcam/FlareClusterLayer#29]
i will realise an effect that when view zoom than 14,  view will remove FlareClusterLayer, and add a FeatureLayer, but the FlareClusterLayer has been execute. below is my code 🔢 
1. init...
![image](https://user-images.githubusercontent.com/8743692/35665380-ff5bdad2-0760-11e8-87b2-bc537e125c1f.png)

2. zoom watch
![image](https://user-images.githubusercontent.com/8743692/35665508-87f41904-0761-11e8-99e5-a460aaf6295d.png)

3. run app, and drag the view 、zoom the view  too many times, the app will be caton ，and print 
```shell
draw-data-3d: xx.xxxxxx ms
```
![image](https://user-images.githubusercontent.com/8743692/35665540-aa72fd24-0761-11e8-8f4c-117ba4b59933.png)
 
the memory is rising
![image](https://user-images.githubusercontent.com/8743692/35665818-9e7a6754-0762-11e8-89ee-ea540cad28ec.png)

**Comment by nickcam** [comment]
Hi mate, by the sounds of it you want to hide the cluster and display a feature layer instead at certain zoom level, did I get that right? An example page where the problem is occurring would be super helpful.

Seems like the scene view doesn't like it for some reason, can't really tell from your code in the images though.

Perhaps instead of removing and adding the layers to the map when zooming, you add both layers to the map up front. When zoom < 14 and you want the cluster layer to be shown, set visible=false on the feature layer. When zoom >= 14, set visible = false on the cluster layer and set the data property of the cluster layer to undefined. That way it will never run through it's draw code. Obviously set the data and visible flag back when you want to change back to the cluster layer. 
Does that make sense?
