### ISSUE TITLE
Arcgis for js 4.9

### ISSUE THREAD

**Issue by JinLongy** [nickcam/FlareClusterLayer#38]
Hi,nick.At first,my English is not good.I have a problem when introducing this FlareClusterLayer_v4.js to my Vue project.I received an error message,but I can't say it very clearly.So please see the attachment I uploaded for details.
![img001](https://user-images.githubusercontent.com/44226522/51021763-722c0300-15bd-11e9-8dcf-e918fb81a1bf.png)
![img002](https://user-images.githubusercontent.com/44226522/51021764-722c0300-15bd-11e9-99b7-836d65106892.png)
![img003](https://user-images.githubusercontent.com/44226522/51021765-72c49980-15bd-11e9-833d-61fc373f246b.png)

**Comment by nickcam** [comment]
Hi @JinLongy, that error suggests that the class hasn't loaded correctly. Have you followed the esri-loader instructions here - [https://github.com/Esri/esri-loader#configuring-dojo](https://github.com/Esri/esri-loader#configuring-dojo) - to include the esri/extras package?

**Comment by JinLongy** [comment]
But I can print this js object to access.
![tim 20190112110828](https://user-images.githubusercontent.com/44226522/51068556-7e19d280-165a-11e9-8123-e6b5d4a5f17f.png)

**Comment by JinLongy** [comment]
I deployed the official api to the local server and placed this file in the esri directory. It stands to reason that you should be able to access this file.

**Comment by nickcam** [comment]
Oh yeah I see it now. In your example you need to instantiate it like this - 
`var layer = new FlareClusterLayer.FlareClusterLayer({options});`

The module imported in the loadModules() call isn't the actual class. It contains the class inside it, so you need to reference the class by using `<module>.<class>`, ie: since you're using FlareClusterLayer as the module name then it is - `FlareClusterLayer.FlareClusterLayer`. 

Let me know how you go.

**Comment by JinLongy** [comment]
Well, it’s ok now. thank you very much.

**Comment by nickcam** [comment]
Ok cool.
