### ISSUE TITLE
legend

### ISSUE THREAD

**Issue by pyalam** [nickcam/FlareClusterLayer#40]
Nick,

I was trying to add legend to the cluster layer but It is showing no legend.How do you add legend to the cluster layer .Could you please look into it.Thanks.

**Comment by nickcam** [comment]
Hi @pyalam, I've never used it with the legend widget, so not surprised it doesn't work. A quick look at the legend api docs though suggests it uses the renderer property of the layer to work out what to put in the legend. [https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Legend.html](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Legend.html). 

You can try setting the renderer property to the same value as the clusterRenderer property. GraphicsLayers don't have a renderer property though, so you'll have to try setting it like so - `clusterLayer["renderer"] = <value here> `

If that doesn't work then it will probably have to wait until it's rewritten to be a subclass of feature layer instead of graphics layer.

**Comment by pyalam** [comment]
Thank you nick.I was trying to add the functioanlity of your cluster layer on zoomsingle click event.But the zoom is not going there.Do you have that functionality by chance .On single click on cluster zoom to the features.

**Comment by nickcam** [comment]
That's certainly not built into the layer itself. Check out the mapview and sceneview click event and hitTest functionality of the api, and you'll be able to make that happen I imagine.
