### ISSUE TITLE
Getting node_module error while running application

### ISSUE THREAD

**Issue by MayurGIS** [nickcam/FlareClusterLayer#50]
Hi @nickcam,
First of all I would like to thank you for this clustering part. I am facing some issue while running your code. I have cloned you code. Then I write "npm install" command in visual code studio. I am getting "no such file or directory, open '..\projects\9-3-2019\FlareClusterLayer\node_modules\.staging\semver-6e4f5872\package.json'. I am missing some libraries or what. I am new to Angular also.

**Comment by nickcam** [comment]
Hi @MayurGIS - hard to say what the issue is sorry. Make sure you've got node and npm installed globally, a fairly recent version as well.

The directory you're running npm install from has to be the root of the project...where the package,json file lives, double check that.

There's no dependency on Angular to run it either...it's just typescript and javascript.
